### ISSUE TITLE
Implementar métricas no hubot-natural

### ISSUE THREAD

**Issue by MatheusFaria** [lappis-unb/hubot-natural#23]
* Número total de usuários
   * Número inteiro de quantidade de usuários

* Quantidade de usuários atendidos pelo bot:
    * Diariamente
    * Mensalmente
    * Anualmente

* Taxa de satisfação pós-atendimento: Deve se ter um feedback do usuário sobre seu grau de satisfação. Quantidade de usuários que:
  * sanaram suas dúvidas?
  * não sanaram?
  * responderam ao feedback?
  * não responderam?

* Ranking de intenções
  * Registro de intenções com maiores ocorrências classificação.
  * Registrar intenção e grau de confiabilidade

* Gatilhos de confusão
  * Registrar conversas que o bot não conseguiu responder.
  * Quantidade de ocorrências de mensagens sem classificação (não identificou intenção)

* Contar quantos pedidos para transferir para um humano
  * Registrar o número de quantidade de pedidos de transferência para humanos

* Taxa de interação
  * Contagem da quantidade de interações
  * Quanto maior as taxas de interação podem significar que os usuários não estão recebendo as respostas que gostariam.

**Comment by joenio** [comment]
creio que essa issue já fechou, certo @MatheusFaria ?
